In [3]:
import random

def lottery():
    for i in range(4):
        yield random.randint(1, 40)
        
    yield random.randint(1, 45)
    
for random_number in lottery():
    print("And the next number is...... %d" %(random_number))

And the next number is...... 35
And the next number is...... 32
And the next number is...... 40
And the next number is...... 12
And the next number is...... 5


In [5]:
var = "This is the sentence which is counted by list comprehension"
sec_var = var.split()
print(sec_var)

['This', 'is', 'the', 'sentence', 'which', 'is', 'counted', 'by', 'list', 'comprehension']


In [9]:
third_var = [len(word) for word in sec_var if word != "the"]
third_var

[4, 2, 8, 5, 2, 7, 2, 4, 13]

In [7]:
#counting no. of letters in particular words accept "the"
sentence = "the quick brown fox jumps over the lazy dog"
words = sentence.split()
word_lengths = [len(word) for word in words if word != "the"]
print(words)
print(word_lengths)

['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
[5, 5, 3, 5, 4, 4, 3]


In [8]:
#printing only positive number
numbers = [34.6, -203.4, 44.9, 68.3, -12.2, 44.6, 12.7]
newlist = [i for i in numbers if i > 0]
print(newlist)

[34.6, 44.9, 68.3, 44.6, 12.7]


In [5]:
#Multiple fucntion

def var(a, b, c, d):
    sum = a + b + c + d
    sub = a - b - c - d
    return sum, sub

print(var(1, 2, 3, 4))


(10, -8)


In [9]:
# MULTIPLE VARIABLE IN FUNCTIONS

def sam(*unlimited):
    return sum(unlimited)
print(sam(1,2,3,4,5,6,7,8,9,10))

55


In [19]:
import re
text = "this is only test"
x = re.findall("ly", text)
print(x)

['ly']


In [21]:
txt = "The rain in Spain"
x = re.findall("Portugal", txt)
print(x)

[]


In [22]:
#this is the way of handling error, also called Exception Handling.
def do_stuff_with_number(n):
    print(n)

def catch_this():
    the_list = (1, 2, 3, 4, 5)

    for i in range(20):
        try:
            do_stuff_with_number(the_list[i])
        except IndexError: # Raised when accessing a non-existing index of a list
            do_stuff_with_number(0)

catch_this()

1
2
3
4
5
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [27]:
a = set(["Jake", "John", "Eric"])
print(a)
b = set(["John", "Jill"])
print(b)

{'John', 'Jake', 'Eric'}
['John', 'Jill']


In [26]:
print(set("my name is Eric and Eric is my name".split()))

{'Eric', 'is', 'name', 'my', 'and'}


In [28]:
a = set(["Jake", "John", "Eric"])
b = set(["John", "Jill"])

print(a.intersection(b))
print(b.intersection(a))

{'John'}
{'John'}


In [29]:
print(a.symmetric_difference(b))
print(b.symmetric_difference(a))

{'Eric', 'Jill', 'Jake'}
{'Jake', 'Eric', 'Jill'}


In [30]:
print(a.difference(b))
print(b.difference(a))

{'Eric', 'Jake'}
{'Jill'}


In [33]:
import json
json_string = json.dumps([1,2,3,4,"a","b","v"])
print(json.loads(json_string))

[1, 2, 3, 4, 'a', 'b', 'v']


In [34]:
import pickle
pickled_string = pickle.dumps([1,2,3])
print(pickle.loads(pickled_string))

[1, 2, 3]


In [37]:
from functools import partial

def multiply(x, y):
    return x * y

dbl = partial(multiply, 2)
print(dbl(3))

6


In [40]:
def sam(x, y):
    var = 2
    ghh = var *(x+y)
    print(ghh)
aa = partial(sam, 2)
aa(5)

14


In [42]:

dir(aa)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'args',
 'func',
 'keywords']

In [44]:
def transmit_to_space(message):
    "This is the enclosing function"
    def data_transmitter():
        "The nested function"
        print(message)

    data_transmitter()

print(transmit_to_space("hullo there!"))

hullo there!
None


In [12]:
def this_is_main(value):
    def this_is_nested(multiplier):
        return value * multiplier

    return this_is_nested
    
multi3 = this_is_main(3)
print(multi3(5))

15


In [3]:
def car(name):
    def model(number):
        var = name + number
        return var
    
    return model
car_name_model = car("bmw")
print(car_name_model("9863ABD"))


bmw9863ABD


In [15]:
def inc(x):
    return x + 1

def dec(x):
    return x - 1

def operatye(func, x):
    result = func(x)
    return result
operatye(inc, 3)


4

In [14]:
operatye(dec, 3)

2

In [26]:
def make_pretty(func):
    def inner():
        print("I got decorated")
        func()
    return inner

@make_pretty
def ordinary():
    print("I am ordinary")
ordinary()

I got decorated
I am ordinary


In [20]:
pretty = make_pretty(ordinary)
pretty()

I got decorated
I am ordinary


In [21]:
ordinary = make_pretty(ordinary)
ordinary()

I got decorated
I am ordinary


# Numpy and Pandas

In [34]:
import numpy as np
arr = [1, 2, 4,5,6,7 ]
a = np.array(arr)
a

array([1, 2, 4, 5, 6, 7])

In [29]:
a.shape

(3,)

In [35]:
a.reshape(3,2)

array([[1, 2],
       [4, 5],
       [6, 7]])

In [53]:
np.ndarray(shape=(1,2,4) )

array([[[4.67221852e-310, 4.67221857e-310, 6.93359996e-310,
         2.64737514e-232],
        [6.93359996e-310, 6.93359996e-310, 2.49933253e-156,
         6.93359996e-310]]])

In [60]:
np.random.seed(10)
np.random.randint(1,10,6)

array([5, 1, 2, 1, 2, 9])

In [61]:
np.pi

3.141592653589793

In [80]:
from fractions import Fraction
num = int(input("Enter the number to find its sine value: "))
sine_value = Fraction(np.sin(num))
print("\nThe sine value of the input number is: ", sine_value)

Enter the number to find its sine value: 1

The sine value of the input number is:  3789648413623927/4503599627370496


In [82]:
import pandas as pd

In [98]:
a = np.ndarray(shape=(4,5))
a

array([[6.93361736e-310, 4.67221881e-310, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [99]:
b = pd.DataFrame(a)
b

0              1    2    3    4
0  6.933617e-310  4.672219e-310  0.0  0.0  0.0
1   0.000000e+00   0.000000e+00  0.0  0.0  0.0
2   0.000000e+00   0.000000e+00  0.0  0.0  0.0
3   0.000000e+00   0.000000e+00  0.0  0.0  0.0

In [103]:
indx = "A B C D E".split()
print(indx)

['A', 'B', 'C', 'D', 'E']


In [105]:
data = pd.DataFrame(a, columns = indx)
print(data)

               A              B    C    D    E
0  6.933617e-310  4.672219e-310  0.0  0.0  0.0
1   0.000000e+00   0.000000e+00  0.0  0.0  0.0
2   0.000000e+00   0.000000e+00  0.0  0.0  0.0
3   0.000000e+00   0.000000e+00  0.0  0.0  0.0


In [107]:
data.describe()

A              B    C    D    E
count   4.000000e+00   4.000000e+00  4.0  4.0  4.0
mean   1.733404e-310  1.168055e-310  0.0  0.0  0.0
std     0.000000e+00   0.000000e+00  0.0  0.0  0.0
min     0.000000e+00   0.000000e+00  0.0  0.0  0.0
25%     0.000000e+00   0.000000e+00  0.0  0.0  0.0
50%     0.000000e+00   0.000000e+00  0.0  0.0  0.0
75%    1.733404e-310  1.168055e-310  0.0  0.0  0.0
max    6.933617e-310  4.672219e-310  0.0  0.0  0.0